[variables]
# 2 GB en megabytes
UPLOAD_MAX_FILESIZE = '2048M'
POST_MAX_SIZE = '2048M'

[phases.setup]
# Localiza php.ini del runtime de Nix y le agrega un upload.ini con los nuevos lÃ­mites
cmds = [
  "UPLOAD_INI_PATH=$(find /nix/store/*-php-*/lib -name php.ini -print0 | head -z -n 1 | rev | cut -c 9- | rev)/upload.ini; echo \"upload_max_filesize=${UPLOAD_MAX_FILESIZE};\" >> $UPLOAD_INI_PATH; echo \"post_max_size=${POST_MAX_SIZE};\" >> $UPLOAD_INI_PATH"
]
